version: '3.1'
services:

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: backend
    container_name: backend
    command: bash -c "sh ./docker/entrypoint.sh"
    env_file:
      - ./docker/.env
    volumes:
      - .:/code
    ports:
      - 80:80
    ######### stdin_open and tty to debug
    stdin_open: true
    tty: true
#    links:
#      - db

  test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python ./weather_api/manage.py test weather.tests
    depends_on:
      - backend
    env_file:
      - ./docker/.env
    volumes:
      - .:/code

  behave:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./docker/.env
    command:  python ./weather_api/manage.py behave weather_api/weather/features

  generate_db_entries:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./docker/.env
    command: python ./weather_api/manage.py generate_db_entries --count 20

