# Generated by Django 4.2.7 on 2023-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='timezone',
            field=models.CharField(max_length=63),
        ),
    ]
