# Generated by Django 4.2.7 on 2023-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weather_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
